name:                websocket-button
version:             0.0.1.0
github:              "krakrjak/websocket-button"
license:             BSD3
author:              "Zac Slade"
maintainer:          "krakrjak@gmail.com"
copyright:           "2019 Zac Slade"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Make a web button
category:            Web
description:         Please see the README on GitHub at <https://github.com/krakrjak/websocket-button#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - servant
  - websockets
  - time
  - data-default

executables:
  websocket-button-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websocket-button
    - data-default

tests:
  websocket-button-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websocket-button
