name:                websocket-button
version:             0.0.1.0
github:              "krakrjak/websocket-button"
license:             BSD2
author:              "Zac Slade"
maintainer:          "krakrjak@gmail.com"
copyright:           "2019 Zac Slade"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Make a web button
category:            Web
description:         Please see the README on GitHub at <https://github.com/krakrjak/websocket-button#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - data-default
  - servant
  - time
  - websockets

executables:
  button-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - dhall
    - fast-logger
    - optparse-applicative
    - servant-server
    - text
    - warp
    - websocket-button

tests:
  button-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websocket-button
